# kubectl apply -f luis-sanchez-37-secret-productos.yml
apiVersion: v1
kind: Secret
metadata:
  name: luis-sanchez-37-secret-productos
  namespace: luis-sanchez-37-namespace-productos
type: Opaque
data:
  DB_HOST: ZGIubW5lYmpwb3VxdG1nZW14dnpnbWsuc3VwYWJhc2UuY28=
  DB_PORT: NTQzMg==
  DB_NAME: cG9zdGdyZXM=
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: THVpc2RldmZsZXgzaw==
  DB_SSL_MODE: cmVxdWlyZQ==
  SERVER_PORT: ODA4MQ==

# echo -n "valor" | base64
