# kubectl apply -f luis-sanchez-37-deployment-productos.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: luis-sanchez-37-deployment-productos
  namespace: luis-sanchez-37-namespace-productos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: luis-sanchez-37-productos
  template:
    metadata:
      labels:
        app: luis-sanchez-37-productos
    spec:
      containers:
      - name: luis-sanchez-37-container-productos
        image: 50luisangelsanchezromero/luis-sanchez-ms-productos:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        envFrom:
        - secretRef:
            name: luis-sanchez-37-secret-productos
