server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: ms-productos

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:db.mnebjpouqtmgemxvzgmk.supabase.co}:${DB_PORT:5432}/${DB_NAME:postgres}?sslMode=${DB_SSL_MODE:require}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:Luisdevflex3k}
    pool:
      enabled: true
      initial-size: 1
      max-size: 3

  sql:
    init:
      mode: ${SQL_INIT_MODE:never}
      schema-locations: classpath:schema.sql

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
