# kubectl apply -f luis-sanchez-37-secret-pedidos.yml
apiVersion: v1
kind: Secret
metadata:
  name: luis-sanchez-37-secret-pedidos
  namespace: luis-sanchez-37-namespace-pedidos
type: Opaque
data:
  DB_HOST: YXdzLTEtdXMtZWFzdC0yLnBvb2xlci5zdXBhYmFzZS5jb20=
  DB_PORT: NTQzMg==
  DB_NAME: cG9zdGdyZXM=
  DB_USER: cG9zdGdyZXMubW5lYmpwb3VxdG1nZW14dnpnbWs=
  DB_PASSWORD: THVpc2RldmZsZXgzaw==
  DB_SSL_MODE: cmVxdWlyZQ==
  SERVER_PORT: ODA4Mg==
  PRODUCTOS_SERVICE_URL: aHR0cDovL2x1aXMtc2FuY2hlei0zNy1zZXJ2aWNlLXByb2R1Y3Rvcy5sdWlzLXNhbmNoZXotMzctbmFtZXNwYWNlLXByb2R1Y3Rvcy5zdmMuY2x1c3Rlci5sb2NhbDo4MDgx

# echo -n "valor" | base64
